### ISSUE TITLE
OWASP Threat Dragon fails on Macintosh

### ISSUE THREAD

**Issue by bcamer** [mike-goodwin/owasp-threat-dragon#166]
I downloaded the MacOS installer from here:
https://github.com/OWASP/threat-dragon-desktop/releases

When I try running it on my MacBook Pro (intel) running Big Sur, it fails and gives this error.

A JavaScript error occurred in the main process
Uncaught Exception:
Error: callback can only be called for once
at Object.module.<computed> [as getPrimaryDisplay] (electron/js2c/browser_init.js:6859:30)
at createMainWindow (/Applications/OWASP-Threat-Dragon.app/Contents/Resources/app.asar/main.js:171:45)
at App.<anonymous> (/Applications/OWASP-Threat-Dragon.app/Contents/Resources/app.asar/main.js:221:18)
at App.emit (events.js:203:13)

**Comment by bcamer** [comment]
This seems to happen when you try and run it when it is already running.  This happened to me when I tried to install it and the first time it failed to run due to iOS not recognizing it from the Apple Store.  After updating the security settings it gave me this error until I exited the initial process I started.
